apiVersion: v1
kind: ConfigMap
metadata:
  name: agp-configmap-default
data:
  SERVER_PORT: "8089"
  LOGGING_CONFIG: /etc/agp/log4j2.xml

  # Installation basepath
  BASE_PATH: /opt/agp
  
  # Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,metrics,prometheus
  
  # Camel spring-boot configurations
  CAMEL_SPRINGBOOT_MESSAGE_HISTORY: "false"
  CAMEL_SPRINGBOOT_TRACING: "false"
  
  # Total timeout for aggregated calls to producers
  AGGREGATE_TIMEOUT: "28000"
  
  # Outpoing parameters for calling services
  VP_INSTANCEID: {{ .Values.skltp.instanceId }}
  VP_DEFAULTRECEIVETIMEOUT: "27000"
  VP_DEFAULTCONNECTTIMEOUT: "2000"
  VP_DEFAULTSERVICEURL: http://vp:8080/vp
  VP_USEAYNCHTTPCONDUIT: "true"
  
  # Outgoing parameters for calling EI-FindContent
  EI_LOGICALADDRESS: "5565594230"
  EI_SENDERID: {{ .Values.skltp.instanceId }}
  EI_FINDCONTENTURL: http://ei-backend:8082/skltp-ei/find-content-service/v1
  EI_CONNECTTIMEOUT: "2000"
  EI_RECEIVETIMEOUT: "20000"
  EI_USEAYNCHTTPCONDUIT: "true"

  # Aggregating service URLs
  GETAGGREGATEDACTIVITIES_V1_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedActivities/service/v1
  GETAGGREGATEDALERTINFORMATION_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedAlertInformation/service/v2
  GETAGGREGATEDALERTINFORMATION_V3_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedAlertInformation/service/v3
  GETAGGREGATEDCARECONTACTS_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedCareContacts/service/v2
  GETAGGREGATEDCARECONTACTS_V3_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedCareContacts/service/v3
  GETAGGREGATEDCAREDOCUMENTATION_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedCareDocumentation/service/v2
  GETAGGREGATEDCAREDOCUMENTATION_V3_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedCareDocumentation/service/v3
  GETAGGREGATEDCAREPLANS_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedCarePlans/service/v2
  GETAGGREGATEDDIAGNOSIS_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedDiagnosis/service/v2
  GETAGGREGATEDECGOUTCOME_V1_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedECGOutcome/service/v1
  GETAGGREGATEDFUNCTIONALSTATUS_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedFunctionalStatus/service/v2
  GETAGGREGATEDIMAGINGOUTCOME_V1_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedImagingOutcome/service/v1
  GETAGGREGATEDLABORATORYORDEROUTCOME_V3_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedLaboratoryOrderOutcome/service/v3
  GETAGGREGATEDLABORATORYORDEROUTCOME_V4_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedLaboratoryOrderOutcome/service/v4
  GETAGGREGATEDMATERNITYMEDICALHISTORY_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedMaternityMedicalHistory/service/v2
  GETAGGREGATEDMEDICATIONHISTORY_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedMedicationHistory/service/v2
  GETAGGREGATEDOBSERVATIONS_V1_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedObservations/service/v1
  GETAGGREGATEDREFERRALOUTCOME_V3_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedReferralOutcome/service/v3
  GETAGGREGATEDREQUESTACTIVITIES_V1_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedRequestActivities/service/v1
  GETAGGREGATEDREQUESTACTIVITIES_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedRequestActivities/service/v2
  GETAGGREGATEDREQUESTEXEMPTIONSTATUSES_V1_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedRequestExemptionStatuses/service/v1
  GETAGGREGATEDSUBJECTOFCARESCHEDULE_V1_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedSubjectOfCareSchedule/service/v1
  GETAGGREGATEDVACCINATIONHISTORY_V1_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedVaccinationHistory/service/v1
  GETAGGREGATEDVACCINATIONHISTORY_V2_INBOUNDSERVICEURL: http://0.0.0.0:9001/GetAggregatedVaccinationHistory/service/v2
  
  # Other services URLs
  RESET_CACHE_URL: http://0.0.0.0:8091/resetcache
  AGP_STATUS_URL: http://0.0.0.0:8080/status
  
  #Takcache configuration
  TAKCACHE_USE_BEHORIGHET_CACHE: "true"
  TAKCACHE_USE_VAGVAL_CACHE: "false"
  TAKCACHE_PERSISTENT_FILE_NAME: /dev/null
  TAKCACHE_ENDPOINT_ADDRESS: http://tak-services-svc:8080/tak-services/SokVagvalsInfo/v2
  
  # Max size of payload loggings
  LOG_MAX_PAYLOAD_SIZE: "49152"
  
  # Service special configuration
  GETAGGREGATEDREQUESTACTIVITIES_V1_RECEIVETIMEOUT: "15000"
  GETAGGREGATEDREQUESTACTIVITIES_V2_RECEIVETIMEOUT: "15000"
  GETAGGREGATEDSUBJECTOFCARESCHEDULE_V1_RECEIVETIMEOUT: "15000"
