apiVersion: v1
kind: ConfigMap
metadata:
  name: agp-configmap-default
data:
  SERVER_PORT: "{{ .Values.server.port }}"
  LOGGING_CONFIG: "{{ .Values.logging.config }}"

  # Installation basepath
  BASE_PATH: "{{ .Values.paths.base }}"

  # Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "{{ .Values.management.endpointsWebExposureInclude | join "," }}"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "{{ .Values.management.endpointPrometheusEnabled }}"

  JAVA_OPTS: "{{ .Values.deployment.javaOpts }}"

  # Camel spring-boot configurations
  CAMEL_SPRINGBOOT_MESSAGE_HISTORY: "{{ .Values.camel.messageHistory }}"
  CAMEL_SPRINGBOOT_TRACING: "{{ .Values.camel.tracing }}"

  # Total timeout for aggregated calls to producers
  AGGREGATE_TIMEOUT: "{{ .Values.aggregate.timeout }}"

  # Outgoing parameters for calling services
  VP_INSTANCEID: "{{ .Values.skltp.instanceId }}"
  VP_DEFAULTRECEIVETIMEOUT: "{{ .Values.vp.defaultReceiveTimeout }}"
  VP_DEFAULTCONNECTTIMEOUT: "{{ .Values.vp.defaultConnectTimeout }}"
  VP_DEFAULTSERVICEURL: "{{ .Values.vp.defaultServiceUrl }}"
  VP_USEAYNCHTTPCONDUIT: "{{ .Values.vp.useAynchHttpConduit }}"

  # Outgoing parameters for calling EI-FindContent
  EI_LOGICALADDRESS: "{{ .Values.ei.logicalAddress }}"
  EI_SENDERID: "{{ .Values.skltp.instanceId }}"
  EI_FINDCONTENTURL: "{{ .Values.ei.findContentUrl }}"
  EI_CONNECTTIMEOUT: "{{ .Values.ei.connectTimeout }}"
  EI_RECEIVETIMEOUT: "{{ .Values.ei.receiveTimeout }}"
  EI_USEAYNCHTTPCONDUIT: "{{ .Values.ei.useAynchHttpConduit }}"

  # Aggregating service URLs
  GETAGGREGATEDACTIVITIES_V1_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedActivities_v1 }}"
  GETAGGREGATEDALERTINFORMATION_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedAlertInformation_v2 }}"
  GETAGGREGATEDALERTINFORMATION_V3_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedAlertInformation_v3 }}"
  GETAGGREGATEDCARECONTACTS_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedCareContacts_v2 }}"
  GETAGGREGATEDCARECONTACTS_V3_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedCareContacts_v3 }}"
  GETAGGREGATEDCAREDOCUMENTATION_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedCareDocumentation_v2 }}"
  GETAGGREGATEDCAREDOCUMENTATION_V3_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedCareDocumentation_v3 }}"
  GETAGGREGATEDCAREPLANS_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedCarePlans_v2 }}"
  GETAGGREGATEDDIAGNOSIS_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedDiagnosis_v2 }}"
  GETAGGREGATEDECGOUTCOME_V1_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedECGOutcome_v1 }}"
  GETAGGREGATEDFUNCTIONALSTATUS_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedFunctionalStatus_v2 }}"
  GETAGGREGATEDIMAGINGOUTCOME_V1_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedImagingOutcome_v1 }}"
  GETAGGREGATEDLABORATORYORDEROUTCOME_V3_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedLaboratoryOrderOutcome_v3 }}"
  GETAGGREGATEDLABORATORYORDEROUTCOME_V4_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedLaboratoryOrderOutcome_v4 }}"
  GETAGGREGATEDMATERNITYMEDICALHISTORY_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedMaternityMedicalHistory_v2 }}"
  GETAGGREGATEDMEDICATIONHISTORY_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedMedicationHistory_v2 }}"
  GETAGGREGATEDOBSERVATIONS_V1_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedObservations_v1 }}"
  GETAGGREGATEDREFERRALOUTCOME_V3_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedReferralOutcome_v3 }}"
  GETAGGREGATEDREQUESTACTIVITIES_V1_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedRequestActivities_v1 }}"
  GETAGGREGATEDREQUESTACTIVITIES_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedRequestActivities_v2 }}"
  GETAGGREGATEDREQUESTEXEMPTIONSTATUSES_V1_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedRequestExemptionStatuses_v1 }}"
  GETAGGREGATEDSUBJECTOFCARESCHEDULE_V1_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedSubjectOfCareSchedule_v1 }}"
  GETAGGREGATEDVACCINATIONHISTORY_V1_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedVaccinationHistory_v1 }}"
  GETAGGREGATEDVACCINATIONHISTORY_V2_INBOUNDSERVICEURL: "{{ .Values.aggServiceUrls.getAggregatedVaccinationHistory_v2 }}"

  # Other services URLs
  RESET_CACHE_URL: "{{ .Values.otherServiceUrls.resetCache }}"
  AGP_STATUS_URL: "{{ .Values.otherServiceUrls.agpStatus }}"

  # TAK cache configuration
  TAKCACHE_USE_BEHORIGHET_CACHE: "{{ .Values.takcache.useBehorighetCache }}"
  TAKCACHE_USE_VAGVAL_CACHE: "{{ .Values.takcache.useVagvalCache }}"
  TAKCACHE_PERSISTENT_FILE_NAME: "{{ .Values.takcache.persistentFileName }}"
  TAKCACHE_ENDPOINT_ADDRESS: "{{ .Values.takcache.endpointAddress }}"

  # Max size of payload loggings
  LOG_MAX_PAYLOAD_SIZE: "{{ .Values.logging.maxPayloadSize }}"

  # Service special configuration
  GETAGGREGATEDREQUESTACTIVITIES_V1_RECEIVETIMEOUT: "{{ .Values.serviceOverrides.getAggregatedRequestActivities_v1.receiveTimeout }}"
  GETAGGREGATEDREQUESTACTIVITIES_V2_RECEIVETIMEOUT: "{{ .Values.serviceOverrides.getAggregatedRequestActivities_v2.receiveTimeout }}"
  GETAGGREGATEDSUBJECTOFCARESCHEDULE_V1_RECEIVETIMEOUT: "{{ .Values.serviceOverrides.getAggregatedSubjectOfCareSchedule_v1.receiveTimeout }}"
