repository: docker.drift.inera.se/ntjp/

deployment:
  replicaCount: 1
  imagePullPolicy: Always
  elasticGrokFilter: camel
  javaOpts: "-XX:MaxRAMPercentage=65"
  resources: {} # Override to specify resources
  initResources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: agp
      maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway

skltp:
  instanceId: SKLTP-DEFAULT-ID

# Environment-specific backwards-compatible service name
vip:
  name: default-ei-vip

# Aggregating services: maven repository, artifacts, and service ports
aggServices:
  repository: https://nexus.drift.inera.se/repository/maven-public/
  artifacts: {} # Override according to the example below to configure services
  # - groupId: se.skltp.aggregatingservices.riv.clinicalprocess.activity.actions
  #   artifactId: GetAggregatedActivities-v1-main
  #   version: 3.0.0
  ports:
    - 9001

# Server configuration
server:
  port: "8089"

# Installation basepath
paths:
  base: /opt/agp

# Logging configuration
logging:
  config: /etc/agp/log4j2.xml
  maxPayloadSize: "49152"

# Actuator / Management
management:
  endpointsWebExposureInclude:
    - health
    - metrics
    - prometheus
  endpointPrometheusEnabled: "true"

# Camel spring-boot configurations
camel:
  messageHistory: "false"
  tracing: "false"

# Total timeout for aggregated calls to producers
aggregate:
  timeout: "28000"

# Outgoing parameters for calling services via VP
vp:
  defaultReceiveTimeout: "27000"
  defaultConnectTimeout: "2000"
  defaultServiceUrl: "http://vp:8080/vp"
  useAynchHttpConduit: "true"

# Outgoing parameters for calling EI-FindContent
ei:
  logicalAddress: "5565594230"
  findContentUrl: "http://ei-backend:8082/skltp-ei/find-content-service/v1"
  connectTimeout: "2000"
  receiveTimeout: "20000"
  useAynchHttpConduit: "true"

# Aggregating service inbound URLs
aggServiceUrls:
  getAggregatedActivities_v1: "http://0.0.0.0:9001/GetAggregatedActivities/service/v1"
  getAggregatedAlertInformation_v2: "http://0.0.0.0:9001/GetAggregatedAlertInformation/service/v2"
  getAggregatedAlertInformation_v3: "http://0.0.0.0:9001/GetAggregatedAlertInformation/service/v3"
  getAggregatedCareContacts_v2: "http://0.0.0.0:9001/GetAggregatedCareContacts/service/v2"
  getAggregatedCareContacts_v3: "http://0.0.0.0:9001/GetAggregatedCareContacts/service/v3"
  getAggregatedCareDocumentation_v2: "http://0.0.0.0:9001/GetAggregatedCareDocumentation/service/v2"
  getAggregatedCareDocumentation_v3: "http://0.0.0.0:9001/GetAggregatedCareDocumentation/service/v3"
  getAggregatedCarePlans_v2: "http://0.0.0.0:9001/GetAggregatedCarePlans/service/v2"
  getAggregatedDiagnosis_v2: "http://0.0.0.0:9001/GetAggregatedDiagnosis/service/v2"
  getAggregatedECGOutcome_v1: "http://0.0.0.0:9001/GetAggregatedECGOutcome/service/v1"
  getAggregatedFunctionalStatus_v2: "http://0.0.0.0:9001/GetAggregatedFunctionalStatus/service/v2"
  getAggregatedImagingOutcome_v1: "http://0.0.0.0:9001/GetAggregatedImagingOutcome/service/v1"
  getAggregatedLaboratoryOrderOutcome_v3: "http://0.0.0.0:9001/GetAggregatedLaboratoryOrderOutcome/service/v3"
  getAggregatedLaboratoryOrderOutcome_v4: "http://0.0.0.0:9001/GetAggregatedLaboratoryOrderOutcome/service/v4"
  getAggregatedMaternityMedicalHistory_v2: "http://0.0.0.0:9001/GetAggregatedMaternityMedicalHistory/service/v2"
  getAggregatedMedicationHistory_v2: "http://0.0.0.0:9001/GetAggregatedMedicationHistory/service/v2"
  getAggregatedObservations_v1: "http://0.0.0.0:9001/GetAggregatedObservations/service/v1"
  getAggregatedReferralOutcome_v3: "http://0.0.0.0:9001/GetAggregatedReferralOutcome/service/v3"
  getAggregatedRequestActivities_v1: "http://0.0.0.0:9001/GetAggregatedRequestActivities/service/v1"
  getAggregatedRequestActivities_v2: "http://0.0.0.0:9001/GetAggregatedRequestActivities/service/v2"
  getAggregatedRequestExemptionStatuses_v1: "http://0.0.0.0:9001/GetAggregatedRequestExemptionStatuses/service/v1"
  getAggregatedSubjectOfCareSchedule_v1: "http://0.0.0.0:9001/GetAggregatedSubjectOfCareSchedule/service/v1"
  getAggregatedVaccinationHistory_v1: "http://0.0.0.0:9001/GetAggregatedVaccinationHistory/service/v1"
  getAggregatedVaccinationHistory_v2: "http://0.0.0.0:9001/GetAggregatedVaccinationHistory/service/v2"

# Other service URLs
otherServiceUrls:
  resetCache: "http://0.0.0.0:8091/resetcache"
  agpStatus: "http://0.0.0.0:8080/status"

# TAK cache configuration
takcache:
  useBehorighetCache: "true"
  useVagvalCache: "false"
  persistentFileName: /dev/null
  endpointAddress: "http://tak-services-svc:8080/tak-services/SokVagvalsInfo/v2"

# Service special configuration (per-service overrides)
serviceOverrides:
  getAggregatedRequestActivities_v1:
    receiveTimeout: "15000"
  getAggregatedRequestActivities_v2:
    receiveTimeout: "15000"
  getAggregatedSubjectOfCareSchedule_v1:
    receiveTimeout: "15000"

environment:
  variables:
    _default_config_maps:
      - agp-configmap-default
    config_maps:
    # Override to supply your own maps.
    secrets:
    # Override to supply your own secrets.

log4j:
  loggers:
    - name: se.skltp.aggregatingservices
      level: INFO
    - name: se.skltp.takcache
      level: INFO
    - name: se.skltp.aggregatingservices.logging
      level: INFO
    - name: se.skltp.aggregatingservices.logging.FindContentResponderInterface
      level: DEBUG
  rootLoggerLevel: WARN

probes:
  startupProbe:
    httpGet:
      path: actuator/health/readiness
      port: actuators
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 5  # 30s initial + 18 failures * 5s period = 120 seconds max startup before failure and restart.
    timeoutSeconds: 4
    successThreshold: 1
    failureThreshold: 18
  livenessProbe:
    httpGet:
      path: actuator/health/liveness
      port: actuators
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    # 3x 10s + 5s timeout allows for up to 45 seconds of non-responsiveness before pod kill-and-restart.
    #    Earliest kill possible 55 seconds after startup completes.
    failureThreshold: 4
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: actuator/health/readiness
      port: actuators
      scheme: HTTP
    # lower initial delay than liveness, but same period, allows traffic to be governed before liveness is tested.
    initialDelaySeconds: 9
    periodSeconds: 10
    timeoutSeconds: 5
    # 1x 10s + timeout 5s allows for up to 15 seconds on non-response before traffic is cut from pod.
    #    Earliest cut possible 24 seconds after startup completes.
    failureThreshold: 1
    successThreshold: 1


